version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: ./TBD.sh all
      - run: mkdir results && mv ./*.json results
      - run: ./deploy.sh $GITHUB_TOKEN

workflows:
  build:
    jobs:
      - build:
        context:
          - GITHUB
